### ISSUE TITLE
Clarify: are gradients considered contentful?

### ISSUE THREAD

**Issue by noamr** [w3c/paint-timing#61]
Currently according to the spec, background images are considered contentful in terms of measuring FCP. The definition of images in CSS also includes gradients. I'm not sure they should be - they're more similar to background colors than they are to images in terms of what "content" is - but in any case the spec should maybe clarify this.

**Comment by npm1** [comment]
I tend to agree that gradients are not very contentful (given that colors aren't). I did a quick test, Chrome currently does consider them as contentful. But I'm open to changing it, and we can mention this in the spec either way.

**Comment by rniwa** [comment]
Related, we really need to more rigorously define what it means for an image to be rendered, or even what an image means in this context.

For example, [https://drafts.csswg.org/css-images-4/#image-values](<image> type) defines the CSS syntax for specifying images in places like `background-image`, and one of the concepts defined there is of an [invalid image](https://drafts.csswg.org/css-images-4/#invalid-image) where url is pointing to a non-existent image. We need to define under which scenarios, anything specified by <image> type is considered as an image and is rendered.

And then for each one of those properties, we need to define under what condition a specified image is considered as rendered. For example, `background-image` has an associated [background painting area](https://drafts.csswg.org/css-backgrounds-3/#background-painting-area). What happens when this background painting area is 0px by 0px?

A [border image](https://drafts.csswg.org/css-backgrounds-3/#border-image-process) with `border-image-width` set to 0px presumably doesn't count?

All these things need to precisely defined.

**Comment by noamr** [comment]
I tried to address this here: https://github.com/w3c/paint-timing/pull/66

**Comment by noamr** [comment]
I believe that https://github.com/w3c/paint-timing/pull/66 addresses this, closing.

**Comment by npm1** [comment]
@noamr so they will not be considered contentful, correct? Once you confirm I can add a test (Chrome will fail it at the moment).

**Comment by noamr** [comment]
> @noamr so they will not be considered contentful, correct? Once you confirm I can add a test (Chrome will fail it at the moment).

Correct. Only loaded images will be considered contentful.

**Comment by rniwa** [comment]
Please don't close an issue until the relevant PR is landed. It's very confusing.

**Comment by noamr** [comment]
> Please don't close an issue until the relevant PR is landed. It's very confusing.

OK, sorry :)

**Comment by noamr** [comment]
Closing now that the PR is landed. https://w3c.github.io/paint-timing/
