### ISSUE TITLE
Should transparent (alpha-value=0) text be considered contentful

### ISSUE THREAD

**Issue by noamr** [w3c/paint-timing#75]
See discussion in https://github.com/w3c/paint-timing/issues/58
Firefox opts out of painting when text has hsla(..., 0) or rgba(..., 0). Maybe the spec should be fixed to comply with that - making fully-transparent text be non-contentful.

**Comment by rniwa** [comment]
That (ignoring text with alpha=0) makes sense to me. @smfr

**Comment by npm1** [comment]
@sefeng211 and @mstange this was discussed at the latest call. We didn't have any strong opinions but there was a slight preference towards considering this text as contentful because it may still become visible when the user searches or highlights it. Would this be something Mozilla could implement?

**Comment by mstange** [comment]
That makes sense! Yes, implementing this in Firefox wouldn't be too hard.

**Comment by noamr** [comment]
Closing this, feel free to reopen if this issue comes back.
